### ISSUE TITLE
add lua bundle

### ISSUE THREAD

**Issue by ghost** [consulo/consulo-lua#1]
![image](https://cloud.githubusercontent.com/assets/10781622/6429329/f16ce37c-c004-11e4-802e-d7de42650131.png)
could not add lua sdk. is it necessary to add it? I cannot invoke lua lib functions without it.

**Comment by VISTALL** [comment]
U can set <none> and play. Adding sdk - will add _stdlibrary_ symbols for resolving, and run functional
